services:
  frontend:
    build:
      context: ./f1_bets_frontend
      dockerfile: Dockerfile
    container_name: f1_bets_frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./f1_bets_backend
      dockerfile: Dockerfile
    container_name: f1_bets_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
